# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)
import torch


### 2. Create a random tensor with shape `(7, 7)`.


In [12]:
# Import torch


# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor

tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [15]:
# Create another random tensor
another_ran_tensor = torch.rand(size=(1,7))
# Perform matrix multiplication 
mul_mat=torch.mm(random_tensor,another_ran_tensor.T)
mul_mat

tensor([[3.4483],
        [1.7395],
        [2.9746],
        [3.0881],
        [1.9608],
        [1.9364],
        [2.6048]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
out1 = torch.rand((7,7))
out2 = torch.rand(size=(1,7))
# Matrix multiply tensors
mul_matrix = torch.mm(out1,out2.T)
mul_matrix

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU

# Create two random tensors on GPU
random_tensor1 = torch.rand(size=(2,3))
random_tensor2 = torch.rand_like(random_tensor1)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
mul_ran_mat=torch.mm(random_tensor1,random_tensor2.T)
mul_ran_mat

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
print(f"max of mul mat is {mul_ran_mat.max()}")
# Find min
print(f"Min of the random Mul matrix is {mul_ran_mat.min()}")

max of mul mat is 0.5617256760597229
Min of the random Mul matrix is 0.3647301197052002


### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max
print(f"Index where max value occurs: {mul_ran_mat.argmax()}")

# Find arg min

print(f"Index where min value occurs: {mul_ran_mat.argmin()}")

Index where max value occurs: 3
Index where min value occurs: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
ran= torch.rand(size=(1,1,1,10))

# Remove single dimensions
ran2 = torch.reshape(ran,[10])

# Print out tensors and their shapes
print(ran,ran.shape)
print(ran2,ran2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
